name: Event based workflow execution

on: 
  push: 
    branches:
      - main

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "----TRIGGERED the main branch workflow - event based----"
